//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelEntities : DbContext
    {
        public OtelEntities()
            : base("name=OtelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLBANKAHAREKETLER> TBLBANKAHAREKETLER { get; set; }
        public virtual DbSet<TBLBANKALAR> TBLBANKALAR { get; set; }
        public virtual DbSet<TBLBIRIMLER> TBLBIRIMLER { get; set; }
        public virtual DbSet<TBLCARIHAREKETLER> TBLCARIHAREKETLER { get; set; }
        public virtual DbSet<TBLCARIKONUKHAREKETLER> TBLCARIKONUKHAREKETLER { get; set; }
        public virtual DbSet<TBLCARILER> TBLCARILER { get; set; }
        public virtual DbSet<TBLCARITURLER> TBLCARITURLER { get; set; }
        public virtual DbSet<TBLDEPARTMANLAR> TBLDEPARTMANLAR { get; set; }
        public virtual DbSet<TBLDURUMLAR> TBLDURUMLAR { get; set; }
        public virtual DbSet<TBLGOREVLER> TBLGOREVLER { get; set; }
        public virtual DbSet<TBLISLEMLER> TBLISLEMLER { get; set; }
        public virtual DbSet<TBLKASAHAREKETLER> TBLKASAHAREKETLER { get; set; }
        public virtual DbSet<TBLKASALAR> TBLKASALAR { get; set; }
        public virtual DbSet<TBLKURLAR> TBLKURLAR { get; set; }
        public virtual DbSet<TBLODALAR> TBLODALAR { get; set; }
        public virtual DbSet<TBLPERSONELLER> TBLPERSONELLER { get; set; }
        public virtual DbSet<TBLREZERVASYONLAR> TBLREZERVASYONLAR { get; set; }
        public virtual DbSet<TBLTELEFONLAR> TBLTELEFONLAR { get; set; }
        public virtual DbSet<TBLURUNGRUPLAR> TBLURUNGRUPLAR { get; set; }
        public virtual DbSet<TBLURUNLER> TBLURUNLER { get; set; }
        public virtual DbSet<TBLUYRUKLAR> TBLUYRUKLAR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
