//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBANKALAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBANKALAR()
        {
            this.TBLBANKAHAREKETLER = new HashSet<TBLBANKAHAREKETLER>();
        }
    
        public int BANKAID { get; set; }
        public string SUBE { get; set; }
        public string BANKAADI { get; set; }
        public string BANKAHESAPNO { get; set; }
        public Nullable<int> KUR { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKAHAREKETLER> TBLBANKAHAREKETLER { get; set; }
        public virtual TBLDURUMLAR TBLDURUMLAR { get; set; }
        public virtual TBLKURLAR TBLKURLAR { get; set; }
    }
}
