//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCARILER()
        {
            this.TBLCARIHAREKETLER = new HashSet<TBLCARIHAREKETLER>();
            this.TBLCARIKONUKHAREKETLER = new HashSet<TBLCARIKONUKHAREKETLER>();
            this.TBLREZERVASYONLAR = new HashSet<TBLREZERVASYONLAR>();
        }
    
        public int CARIID { get; set; }
        public string CARIADSOYAD { get; set; }
        public string CARIADRES { get; set; }
        public string CARITC { get; set; }
        public string VERGIDAIRE { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string KIMLIKFOTO1 { get; set; }
        public string KIMLIKFOTO2 { get; set; }
        public Nullable<int> CARITUR { get; set; }
        public string YETKILI { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> UYRUK { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKETLER> TBLCARIHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKONUKHAREKETLER> TBLCARIKONUKHAREKETLER { get; set; }
        public virtual TBLCARITURLER TBLCARITURLER { get; set; }
        public virtual TBLDURUMLAR TBLDURUMLAR { get; set; }
        public virtual TBLUYRUKLAR TBLUYRUKLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREZERVASYONLAR> TBLREZERVASYONLAR { get; set; }
    }
}
