//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDURUMLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLDURUMLAR()
        {
            this.TBLBANKAHAREKETLER = new HashSet<TBLBANKAHAREKETLER>();
            this.TBLBANKAHAREKETLER1 = new HashSet<TBLBANKAHAREKETLER>();
            this.TBLBANKALAR = new HashSet<TBLBANKALAR>();
            this.TBLBIRIMLER = new HashSet<TBLBIRIMLER>();
            this.TBLCARIHAREKETLER = new HashSet<TBLCARIHAREKETLER>();
            this.TBLCARIKONUKHAREKETLER = new HashSet<TBLCARIKONUKHAREKETLER>();
            this.TBLCARIKONUKHAREKETLER1 = new HashSet<TBLCARIKONUKHAREKETLER>();
            this.TBLCARILER = new HashSet<TBLCARILER>();
            this.TBLCARITURLER = new HashSet<TBLCARITURLER>();
            this.TBLGOREVLER = new HashSet<TBLGOREVLER>();
            this.TBLISLEMLER = new HashSet<TBLISLEMLER>();
            this.TBLKASAHAREKETLER = new HashSet<TBLKASAHAREKETLER>();
            this.TBLKASALAR = new HashSet<TBLKASALAR>();
            this.TBLKURLAR = new HashSet<TBLKURLAR>();
            this.TBLODALAR = new HashSet<TBLODALAR>();
            this.TBLPERSONELLER = new HashSet<TBLPERSONELLER>();
            this.TBLREZERVASYONLAR = new HashSet<TBLREZERVASYONLAR>();
            this.TBLTELEFONLAR = new HashSet<TBLTELEFONLAR>();
            this.TBLURUNGRUPLAR = new HashSet<TBLURUNGRUPLAR>();
            this.TBLURUNLER = new HashSet<TBLURUNLER>();
            this.TBLURUNLER1 = new HashSet<TBLURUNLER>();
            this.TBLUYRUKLAR = new HashSet<TBLUYRUKLAR>();
            this.TBLDEPARTMANLAR = new HashSet<TBLDEPARTMANLAR>();
        }
    
        public int DURUMID { get; set; }
        public string DURUMAD { get; set; }
        public string KATEGORI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKAHAREKETLER> TBLBANKAHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKAHAREKETLER> TBLBANKAHAREKETLER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKALAR> TBLBANKALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBIRIMLER> TBLBIRIMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKETLER> TBLCARIHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKONUKHAREKETLER> TBLCARIKONUKHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKONUKHAREKETLER> TBLCARIKONUKHAREKETLER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARILER> TBLCARILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARITURLER> TBLCARITURLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLGOREVLER> TBLGOREVLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLISLEMLER> TBLISLEMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASAHAREKETLER> TBLKASAHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASALAR> TBLKASALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKURLAR> TBLKURLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLODALAR> TBLODALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERSONELLER> TBLPERSONELLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLREZERVASYONLAR> TBLREZERVASYONLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTELEFONLAR> TBLTELEFONLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUNGRUPLAR> TBLURUNGRUPLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUNLER> TBLURUNLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUNLER> TBLURUNLER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUYRUKLAR> TBLUYRUKLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDEPARTMANLAR> TBLDEPARTMANLAR { get; set; }
    }
}
