//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGOREVLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLGOREVLER()
        {
            this.TBLPERSONELLER = new HashSet<TBLPERSONELLER>();
        }
    
        public int GOREVID { get; set; }
        public string GOREVAD { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLDEPARTMANLAR TBLDEPARTMANLAR { get; set; }
        public virtual TBLDURUMLAR TBLDURUMLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERSONELLER> TBLPERSONELLER { get; set; }
    }
}
