//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASALAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKASALAR()
        {
            this.TBLKASAHAREKETLER = new HashSet<TBLKASAHAREKETLER>();
        }
    
        public int KASAID { get; set; }
        public string KASAADI { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<decimal> GIRENDEGER { get; set; }
        public Nullable<decimal> CIKANDEGER { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLDURUMLAR TBLDURUMLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASAHAREKETLER> TBLKASAHAREKETLER { get; set; }
    }
}
