//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONELLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPERSONELLER()
        {
            this.TBLBANKAHAREKETLER = new HashSet<TBLBANKAHAREKETLER>();
            this.TBLCARIHAREKETLER = new HashSet<TBLCARIHAREKETLER>();
            this.TBLCARIKONUKHAREKETLER = new HashSet<TBLCARIKONUKHAREKETLER>();
            this.TBLKASAHAREKETLER = new HashSet<TBLKASAHAREKETLER>();
            this.TBLURUNLER = new HashSet<TBLURUNLER>();
        }
    
        public int PERSONELID { get; set; }
        public string ADSOYAD { get; set; }
        public string PERSONELTC { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string KANGRUBU { get; set; }
        public Nullable<System.DateTime> ISEGIRISTARIH { get; set; }
        public Nullable<System.DateTime> ISCIKISTARIH { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<int> GOREV { get; set; }
        public string YETKISI { get; set; }
        public string SIFRE { get; set; }
        public string KIMLIKON { get; set; }
        public string KIMLIKARKA { get; set; }
        public string EHLIYET { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBANKAHAREKETLER> TBLBANKAHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIHAREKETLER> TBLCARIHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCARIKONUKHAREKETLER> TBLCARIKONUKHAREKETLER { get; set; }
        public virtual TBLDEPARTMANLAR TBLDEPARTMANLAR { get; set; }
        public virtual TBLDURUMLAR TBLDURUMLAR { get; set; }
        public virtual TBLGOREVLER TBLGOREVLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKASAHAREKETLER> TBLKASAHAREKETLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLURUNLER> TBLURUNLER { get; set; }
    }
}
