//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> URUNGRUP { get; set; }
        public Nullable<int> BIRIM { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> KUR { get; set; }
        public Nullable<decimal> GIREN { get; set; }
        public Nullable<decimal> CIKAN { get; set; }
        public Nullable<decimal> KALAN { get; set; }
        public Nullable<byte> KDV { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<int> DURUM { get; set; }
    
        public virtual TBLBIRIMLER TBLBIRIMLER { get; set; }
        public virtual TBLDURUMLAR TBLDURUMLAR { get; set; }
        public virtual TBLDURUMLAR TBLDURUMLAR1 { get; set; }
        public virtual TBLPERSONELLER TBLPERSONELLER { get; set; }
        public virtual TBLURUNGRUPLAR TBLURUNGRUPLAR { get; set; }
    }
}
